-- Run this in your Supabase SQL Editor

-- 1. Create the high_scores table
create table highscores (
  id bigint generated by default as identity primary key,
  name text not null,
  score integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable Row Level Security (RLS)
alter table highscores enable row level security;

-- 3. Create Policy to allow anyone to read scores (SELECT)
create policy "Allow public read access"
on highscores
for select
to anon
using (true);

-- 4. Create Policy to allow anyone to insert scores (INSERT)
create policy "Allow public insert access"
on highscores
for insert
to anon
with check (true);

-- 5. Helper view (optional, but good for management)
-- No special view needed for this simple table.
